on: push
name: build
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1
      - name: compile
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.18.3'
          args: '--avoid-cfg-tarpaulin -- --test-threads 1'
      - name: check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: clippy lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
      - if: matrix.rust == 'stable'
        name: Upload to codecov.io
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
  cd:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
    needs: ci
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true
        components: rustfmt, clippy
    - name: build release artifact
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    - name: publish
      run: echo "Not sure where to put it yet ..."
